Update YamlMangl calls to check the exit code.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,13 +22,27 @@ jobs:
     - run: dotnet new tool-manifest
 
     - name: Install Ledgerscope YamlMangl
-      run: dotnet tool install Ledgerscope.YamlMangl
+      run: |
+        echo "Installing YamlMangl"
+        dotnet tool install Ledgerscope.YamlMangl
 
-    - name: Generate xero_accounting_output.yaml from YamlMangl
-      run: dotnet yamlmangl merge -input ./xero_accounting.yaml -delta ./xero_accounting_delta.yaml -output ./xero_accounting_output.yaml -headerType full
+    - name: First merge, generating xero_accounting_output.yaml
+      run: |
+        echo "First merge"
+        dotnet yamlmangl merge -input ./xero_accounting.yaml -delta ./xero_accounting_delta.yaml -output ./xero_accounting_output.yaml -headerType full
+        if [ $? -ne 0 ]; then
+          echo "YamlMangl first merge failed with exit code $?"
+          exit 1
+        fi
 
-    - name: Run YamlMangl with Ledgerscope delta yaml
-      run: dotnet yamlmangl merge -input ./xero_accounting_output.yaml -delta ./xero_accounting_ls_delta.yaml -output ./xero_accounting_ls_output.yaml -headerType full
+    - name: Second merge, generating xero_accounting_ls_output.yaml
+      run: |
+        echo "Second merge"
+        dotnet yamlmangl merge -input ./xero_accounting_output.yaml -delta ./xero_accounting_ls_delta.yaml -output ./xero_accounting_ls_output.yaml -headerType full
+        if [ $? -ne 0 ]; then
+          echo "YamlMangl second merge failed with exit code $?"
+          exit 1
+        fi
 
     - name: Setup NuGet
       run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
